### ISSUE TITLE
Free Gift bug - It shows a free sticker pack with stickers

### ISSUE THREAD

**Issue by AnushPatel** [gatsbyjs/store.gatsbyjs.org#246]
If you try to order a pack of stickers - The site shows in the cart "We will add the Gatsby Sticker Pack as a FREE bonus to your order!" I don't know if that's the intention...

**Comment by steoneill** [comment]
@jlengstorf  is this a bug? Happy to fix if it is!

**Comment by jlengstorf** [comment]
@AnushPatel Good catch!

@steoneill this is definitely a bug. We'd want to check for carts with _only_ stickers in them and hide the “free stickers” callout box.

Let me know if you still want to take this. Thanks!

**Comment by steoneill** [comment]
I'll assign and crack on @jlengstorf !

**Comment by NeverMendel** [comment]
I can work on it! @steoneill Would you mind if I take it?

**Comment by jlengstorf** [comment]
@NeverMendel I believe @steoneill is on this one. Thanks so much for volunteering, though!

**Comment by KirankumarAmbati** [comment]
Hello everyone, is this issue still open ? If yes, I would like to work on it! 😃

**Comment by steoneill** [comment]
Feel free to take over!! I've not had as much time recently as i'd hoped! :(

**Comment by KirankumarAmbati** [comment]
Thanks for the update @steoneill ! I'll start working on it. :)

**Comment by KirankumarAmbati** [comment]
Assigned to myself

**Comment by KirankumarAmbati** [comment]
Fixed and raised PR for this. #264

**Comment by jlengstorf** [comment]
Thanks @KirankumarAmbati!

**Comment by igeligel** [comment]
I think this bug is still existing. The Id changed to something like `Z2lkOi8vc2hvcGlmeS9DaGVja291dExpbmVJdGVtLzEyMjM5NzcyODc2ODg4MD9jaGVja291dD00YWI5OGRmNDQ0ZGE2NTA5ZjdjYjI4MDI4NzBkMDBhNQ==`. I will create a PR fixing this.

![](https://i.imgur.com/axr2Bum.png)

**Comment by jlengstorf** [comment]
Hmm... looks like you're right. Anyone want to tackle a fix?

**Comment by nrator** [comment]
Do you prefer updating the hard-coded id or would you consider setting a minimum subtotal (e.g. $10) for FREE bonus(Gatsby Sticker Pack)? 
Let me know and I would like to work on it as my first contribution!

**Comment by simjes** [comment]
@jlengstorf I'll take a look, do you have any suggestions for a more permanent fix than just changing the ID?
